version: "3"

services:
  redis:
    image: redis:latest
    container_name: gin-app-redis
    #    restart: always
    ports:
      - "6379:6379"
    volumes:
      - gin-app-redis:/data
    env_file:
      - config/redis/redis.env

  postgres:
    image: postgres:latest
    container_name: gin-app-postgres
    #    restart: always
    ports:
      - "5432:5432"
    volumes:
      - gin-app-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${PASSWORD}
      TZ: Asia/Shanghai

  mongodb:
    image: mongo:latest
    container_name: gin-app-mongodb
    #    restart: always
    ports:
      - "27017:27017"
    volumes:
      - gin-app-mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${PASSWORD}

  grafana:
    image: grafana/grafana:latest
    container_name: gin-app-grafana
    #    restart: always
    volumes:
      - gin-app-grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: ${PASSWORD}

  loki:
    image: grafana/loki:latest
    container_name: gin-app-loki
    #    restart: always
    command: -config.file=/etc/loki/loki.yaml
    volumes:
      - ./config/loki/loki.yaml:/etc/loki/loki.yaml
      - gin-app-loki:/loki
    ports:
      - "3100:3100"

  promtail:
    image: grafana/promtail:latest
    container_name: gin-app-promtail
    #    restart: always
    command: -config.file=/etc/promtail/promtail.yaml
    volumes:
      - ./config/promtail/promtail.yaml:/etc/promtail/promtail.yaml
      - /var/log:/var/log

  etcd:
    image: quay.io/coreos/etcd:latest
    container_name: gin-app-etcd
    #    restart: always
    hostname: etcd
    ports:
      - "2379:2379"
      - "2380:2380"
    environment:
      ETCD_DATA_DIR: /etcd-data
      ETCD_NAME: etcd
      ETCDCTL_API: 3
      #ETCD_ROOT_PASSWORD: ${PASSWORD}
      ALLOW_NONE_AUTHENTICATION: yes
      # ETCD_ADVERTISE_CLIENT_URLS: http://0.0.0.0:2379
      # ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      # ETCD_INITIAL_ADVERTISE_PEER_URLS: http://0.0.0.0:2380
      # ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
    command:
      - /usr/local/bin/etcd
      - --data-dir=/etcd-data
      - --name
      - etcd
      - --initial-advertise-peer-urls
      - http://etcd:2380
      - --listen-peer-urls
      - http://0.0.0.0:2380
      - --advertise-client-urls
      - http://etcd:2379
      - --listen-client-urls
      - http://0.0.0.0:2379
    volumes:
      - gin-app-etcd:/etcd-data

  e3w:
    image: soyking/e3w:latest
    container_name: gin-app-e3w
    #    restart: always
    volumes:
      - ./config/e3w/config.ini:/app/conf/config.default.ini
    ports:
      - "8880:8080"
    depends_on:
      - etcd

volumes:
  gin-app-postgres:
  gin-app-mysql:
  gin-app-redis:
  gin-app-mongodb:
  gin-app-grafana:
  gin-app-loki:
  gin-app-etcd:

networks:
  gin-app: