version: "3"

services:
  app:
    container_name: gin-app
    restart: always
    build: .
    ports:
      - "8888:8888"
      - "9999:9999"
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
        loki-retries: "5"
        loki-batch-size: "400"
        loki-external-labels: "container_name={{.Name}},container_id={{.ID}}"

networks:
  gin-app: